version: "3"

services:
  node:
    build: ./
    ports:
      - 3000:3000
      - 4000:4000
      - 5555:5555
    stdin_open: true
    volumes:
      - .:/node
    #   - ./dev/aws/:/root/.aws/
    #   - ./dev/amplify:/root/.amplify/
    tty: true
    networks:
      - app-net
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    command: --replSet rs0
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ./data/mongo:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-net

volumes: 
    mongo:
networks:
  app-net:
    driver: bridge